# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 21:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0002_auto_20160717_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 18, 21, 50, 29, 853817, tzinfo=utc)),
        ),
    ]
