# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 22:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0003_auto_20160718_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 18, 22, 35, 14, 900459, tzinfo=utc)),
        ),
    ]
