# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0009_auto_20160721_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 26, 9, 53, 8, 744331, tzinfo=utc)),
        ),
    ]
