# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 23:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0010_auto_20160726_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 1, 23, 19, 10, 118185, tzinfo=utc)),
        ),
    ]
