# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 13:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0012_auto_20160802_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 3, 13, 12, 33, 14454, tzinfo=utc)),
        ),
    ]
