# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0013_auto_20160803_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 13, 14, 27, 511666, tzinfo=utc)),
        ),
    ]
