# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 13:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0014_auto_20160804_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 4, 13, 30, 50, 513966, tzinfo=utc)),
        ),
    ]
