# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 10:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0017_auto_20160805_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 5, 10, 20, 1, 861643, tzinfo=utc)),
        ),
    ]
