# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('magazines', '0019_auto_20160809_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='subscription_end',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 12, 11, 24, 11, 713912, tzinfo=utc)),
        ),
    ]
